# Generated by Django 5.2 on 2025-04-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(blank=True, max_length=20, null=True)),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('batch_no', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('session', models.CharField(blank=True, max_length=20, null=True)),
                ('lab_venue', models.CharField(blank=True, max_length=50, null=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('regno', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CredentialsManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('student_strength', models.IntegerField(blank=True, null=True)),
                ('session', models.CharField(max_length=50)),
                ('lab_venue', models.CharField(max_length=50)),
                ('ctc_faculty_id', models.CharField(max_length=20)),
                ('ctc_faculty_name', models.CharField(max_length=100)),
                ('ctc_faculty_mail_id', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name_plural': 'Credentials Manager',
                'unique_together': {('course_code', 'batch_no', 'date', 'session')},
            },
        ),
        migrations.CreateModel(
            name='LabDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('batch_no', models.CharField(max_length=10)),
                ('faculty_id', models.CharField(max_length=20)),
                ('faculty_name', models.CharField(max_length=100)),
                ('asst_fac1_id', models.CharField(blank=True, max_length=20, null=True)),
                ('asst_fac1_name', models.CharField(blank=True, max_length=100, null=True)),
                ('asst_fac2_id', models.CharField(blank=True, max_length=20, null=True)),
                ('asst_fac2_name', models.CharField(blank=True, max_length=100, null=True)),
                ('ctc_lab_no', models.CharField(max_length=20)),
                ('day', models.CharField(max_length=20)),
                ('hours', models.CharField(max_length=50)),
                ('ctc_fac_id', models.CharField(max_length=20)),
                ('ctc_fac_name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Lab details',
                'unique_together': {('course_code', 'course_name', 'batch_no')},
            },
        ),
        migrations.CreateModel(
            name='ExamAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(max_length=20)),
                ('lab_venue', models.CharField(max_length=50)),
                ('student_strength', models.IntegerField(blank=True, null=True)),
                ('lab_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_allocations', to='kitslab.labdetails')),
            ],
            options={
                'verbose_name_plural': 'Exam Allocation',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('session', models.CharField(max_length=20)),
                ('lab_venue', models.CharField(max_length=20)),
                ('status', models.BooleanField(default=False)),
                ('student_strength', models.IntegerField(blank=True, null=True)),
                ('lab_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='kitslab.labdetails')),
            ],
            options={
                'verbose_name_plural': 'Availabilities',
            },
        ),
        migrations.CreateModel(
            name='StudentsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_regno', models.CharField(max_length=20, unique=True)),
                ('student_name', models.CharField(max_length=100)),
                ('lab_details', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='kitslab.labdetails')),
            ],
            options={
                'verbose_name_plural': 'Student details',
            },
        ),
    ]
