# Generated by Django 5.2 on 2025-04-11 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsmanager',
            name='last_generated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
