# Generated by Django 5.2 on 2025-04-12 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0002_credentialsmanager_last_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedcredential',
            name='batch_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='generatedcredential',
            name='session',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
