# Generated by Django 5.2 on 2025-04-12 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0003_alter_generatedcredential_batch_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentialsmanager',
            name='batch_no',
            field=models.CharField(max_length=20),
        ),
    ]
