# Generated by Django 5.2 on 2025-04-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0004_alter_credentialsmanager_batch_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialsmanager',
            name='serial_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='generatedcredential',
            name='serial_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
