# Generated by Django 5.2 on 2025-04-15 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0005_credentialsmanager_serial_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='credentialsmanager',
            old_name='serial_no',
            new_name='session_no',
        ),
        migrations.RenameField(
            model_name='generatedcredential',
            old_name='serial_no',
            new_name='session_no',
        ),
    ]
