# Generated by Django 5.2 on 2025-04-15 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0006_rename_serial_no_credentialsmanager_session_no_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='credentialsmanager',
            unique_together=set(),
        ),
    ]
