# Generated by Django 5.2 on 2025-04-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0007_alter_credentialsmanager_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('year', models.IntegerField()),
                ('degree', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=200)),
                ('num_slots', models.IntegerField()),
                ('os_required', models.CharField(max_length=100)),
                ('software_required_version', models.CharField(max_length=100)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
