# Generated by Django 5.2 on 2025-04-24 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0008_assignedcourses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedcourses',
            name='os_required',
        ),
        migrations.RemoveField(
            model_name='assignedcourses',
            name='software_required_version',
        ),
        migrations.AddField(
            model_name='assignedcourses',
            name='os_required_license',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assignedcourses',
            name='os_required_opensource',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assignedcourses',
            name='software_required_version_license',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='assignedcourses',
            name='software_required_version_opensource',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
