# Generated by Django 5.2 on 2025-04-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0009_remove_assignedcourses_os_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcourses',
            name='remarks',
            field=models.CharField(blank=True, null=True),
        ),
    ]
