# Generated by Django 5.2 on 2025-05-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0010_alter_assignedcourses_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcourses',
            name='num_slots',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignedcourses',
            name='semester',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignedcourses',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
