# Generated by Django 5.2 on 2025-05-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0012_rename_os_required_license_assignedcourses_os_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcourses',
            name='nnumberofcredits',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
