# Generated by Django 5.2 on 2025-05-08 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0013_assignedcourses_nnumberofcredits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedcourses',
            old_name='nnumberofcredits',
            new_name='numberofcredits',
        ),
    ]
