# Generated by Django 5.2 on 2025-05-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kitslab', '0014_rename_nnumberofcredits_assignedcourses_numberofcredits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignedcourses',
            old_name='branch',
            new_name='programme',
        ),
    ]
