# Generated by Django 5.2 on 2025-04-21 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField()),
                ('semester', models.CharField(max_length=10)),
                ('year', models.CharField(max_length=10)),
                ('degree', models.CharField(max_length=20)),
                ('branch', models.CharField(max_length=50)),
                ('course_code', models.CharField(max_length=20)),
                ('course_name', models.CharField(max_length=100)),
                ('num_slots', models.CharField(max_length=20)),
                ('os_required', models.CharField(max_length=50)),
                ('software_required', models.IntegerField()),
                ('software_version', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=200)),
            ],
        ),
    ]
