# Generated by Django 5.2 on 2025-04-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labrequest',
            name='date',
        ),
    ]
