# Generated by Django 5.2 on 2025-04-22 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_remove_labrequest_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labrequest',
            old_name='software_version',
            new_name='software_required_version',
        ),
        migrations.RemoveField(
            model_name='labrequest',
            name='software_required',
        ),
    ]
