# Generated by Django 5.2 on 2025-05-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0005_remove_labrequest_os_required_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labrequest',
            old_name='os_required_license',
            new_name='os_required',
        ),
        migrations.RemoveField(
            model_name='labrequest',
            name='os_required_opensource',
        ),
        migrations.AddField(
            model_name='labrequest',
            name='num_batches',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
