# Generated by Django 5.2 on 2025-05-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0007_labrequest_numberofcredits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labrequest',
            name='numberofcredits',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
    ]
