# Generated by Django 5.2 on 2025-05-14 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0008_alter_labrequest_numberofcredits'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labrequest',
            old_name='branch',
            new_name='programme',
        ),
    ]
